# Configuration file for `prek`, a git hook framework written in Rust.
# See https://prek.j178.dev for more information.
#:schema https://www.schemastore.org/prek.json

[[repos]]
repo = "https://github.com/pre-commit/pre-commit-hooks"
rev = "v6.0.0"
hooks = [
  { id = "trailing-whitespace" },
  { id = "end-of-file-fixer" },
  { id = "check-yaml" },
  { id = "check-added-large-files" },
  { id = "check-merge-conflict" }
]

[[repos]]
repo = "local"

[[repos.hooks]]
id = "go-lint"
name = "Go lint"
entry = "mise exec -- golangci-lint run"
language = "system"
types = ["go"]
pass_filenames = false

[[repos.hooks]]
id = "go-format"
name = "Go formatting"
entry = "mise exec -- golangci-lint fmt --diff"
language = "system"
types = ["go"]
pass_filenames = false

[[repos.hooks]]
id = "proto-lint"
name = "Protobuf lint"
entry = "mise exec -- buf lint"
language = "system"
files = '\.proto$|^buf\.yaml$'
pass_filenames = false

[[repos.hooks]]
id = "proto-format"
name = "Protobuf formatting"
entry = "mise exec -- buf format --diff --exit-code"
language = "system"
files = '\.proto$|^buf\.yaml$'
pass_filenames = false
