// Runtime Protocol v1. Field numbers are stable once released.

// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v7.36.1
// source: devsy/runtime/v1/runtime.proto

package runtimev1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	RuntimeDriver_Info_FullMethodName                  = "/devsy.runtime.v1.RuntimeDriver/Info"
	RuntimeDriver_Preflight_FullMethodName             = "/devsy.runtime.v1.RuntimeDriver/Preflight"
	RuntimeDriver_ProvisioningPreflight_FullMethodName = "/devsy.runtime.v1.RuntimeDriver/ProvisioningPreflight"
	RuntimeDriver_Find_FullMethodName                  = "/devsy.runtime.v1.RuntimeDriver/Find"
	RuntimeDriver_TargetArchitecture_FullMethodName    = "/devsy.runtime.v1.RuntimeDriver/TargetArchitecture"
	RuntimeDriver_RunImage_FullMethodName              = "/devsy.runtime.v1.RuntimeDriver/RunImage"
	RuntimeDriver_Start_FullMethodName                 = "/devsy.runtime.v1.RuntimeDriver/Start"
	RuntimeDriver_Stop_FullMethodName                  = "/devsy.runtime.v1.RuntimeDriver/Stop"
	RuntimeDriver_Delete_FullMethodName                = "/devsy.runtime.v1.RuntimeDriver/Delete"
	RuntimeDriver_Exec_FullMethodName                  = "/devsy.runtime.v1.RuntimeDriver/Exec"
	RuntimeDriver_Logs_FullMethodName                  = "/devsy.runtime.v1.RuntimeDriver/Logs"
)

// RuntimeDriverClient is the client API for RuntimeDriver service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type RuntimeDriverClient interface {
	Info(ctx context.Context, in *InfoRequest, opts ...grpc.CallOption) (*InfoResponse, error)
	Preflight(ctx context.Context, in *PreflightRequest, opts ...grpc.CallOption) (*PreflightResponse, error)
	ProvisioningPreflight(ctx context.Context, in *ProvisioningPreflightRequest, opts ...grpc.CallOption) (*ProvisioningPreflightResponse, error)
	Find(ctx context.Context, in *FindRequest, opts ...grpc.CallOption) (*FindResponse, error)
	TargetArchitecture(ctx context.Context, in *TargetArchitectureRequest, opts ...grpc.CallOption) (*TargetArchitectureResponse, error)
	RunImage(ctx context.Context, in *RunImageRequest, opts ...grpc.CallOption) (*RunImageResponse, error)
	Start(ctx context.Context, in *StartRequest, opts ...grpc.CallOption) (*StartResponse, error)
	Stop(ctx context.Context, in *StopRequest, opts ...grpc.CallOption) (*StopResponse, error)
	Delete(ctx context.Context, in *DeleteRequest, opts ...grpc.CallOption) (*DeleteResponse, error)
	Exec(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[ExecClientMessage, ExecServerMessage], error)
	Logs(ctx context.Context, in *LogsRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[OutputChunk], error)
}

type runtimeDriverClient struct {
	cc grpc.ClientConnInterface
}

func NewRuntimeDriverClient(cc grpc.ClientConnInterface) RuntimeDriverClient {
	return &runtimeDriverClient{cc}
}

func (c *runtimeDriverClient) Info(ctx context.Context, in *InfoRequest, opts ...grpc.CallOption) (*InfoResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(InfoResponse)
	err := c.cc.Invoke(ctx, RuntimeDriver_Info_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *runtimeDriverClient) Preflight(ctx context.Context, in *PreflightRequest, opts ...grpc.CallOption) (*PreflightResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PreflightResponse)
	err := c.cc.Invoke(ctx, RuntimeDriver_Preflight_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *runtimeDriverClient) ProvisioningPreflight(ctx context.Context, in *ProvisioningPreflightRequest, opts ...grpc.CallOption) (*ProvisioningPreflightResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ProvisioningPreflightResponse)
	err := c.cc.Invoke(ctx, RuntimeDriver_ProvisioningPreflight_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *runtimeDriverClient) Find(ctx context.Context, in *FindRequest, opts ...grpc.CallOption) (*FindResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(FindResponse)
	err := c.cc.Invoke(ctx, RuntimeDriver_Find_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *runtimeDriverClient) TargetArchitecture(ctx context.Context, in *TargetArchitectureRequest, opts ...grpc.CallOption) (*TargetArchitectureResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(TargetArchitectureResponse)
	err := c.cc.Invoke(ctx, RuntimeDriver_TargetArchitecture_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *runtimeDriverClient) RunImage(ctx context.Context, in *RunImageRequest, opts ...grpc.CallOption) (*RunImageResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RunImageResponse)
	err := c.cc.Invoke(ctx, RuntimeDriver_RunImage_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *runtimeDriverClient) Start(ctx context.Context, in *StartRequest, opts ...grpc.CallOption) (*StartResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(StartResponse)
	err := c.cc.Invoke(ctx, RuntimeDriver_Start_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *runtimeDriverClient) Stop(ctx context.Context, in *StopRequest, opts ...grpc.CallOption) (*StopResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(StopResponse)
	err := c.cc.Invoke(ctx, RuntimeDriver_Stop_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *runtimeDriverClient) Delete(ctx context.Context, in *DeleteRequest, opts ...grpc.CallOption) (*DeleteResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeleteResponse)
	err := c.cc.Invoke(ctx, RuntimeDriver_Delete_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *runtimeDriverClient) Exec(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[ExecClientMessage, ExecServerMessage], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &RuntimeDriver_ServiceDesc.Streams[0], RuntimeDriver_Exec_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[ExecClientMessage, ExecServerMessage]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type RuntimeDriver_ExecClient = grpc.BidiStreamingClient[ExecClientMessage, ExecServerMessage]

func (c *runtimeDriverClient) Logs(ctx context.Context, in *LogsRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[OutputChunk], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &RuntimeDriver_ServiceDesc.Streams[1], RuntimeDriver_Logs_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[LogsRequest, OutputChunk]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type RuntimeDriver_LogsClient = grpc.ServerStreamingClient[OutputChunk]

// RuntimeDriverServer is the server API for RuntimeDriver service.
// All implementations must embed UnimplementedRuntimeDriverServer
// for forward compatibility.
type RuntimeDriverServer interface {
	Info(context.Context, *InfoRequest) (*InfoResponse, error)
	Preflight(context.Context, *PreflightRequest) (*PreflightResponse, error)
	ProvisioningPreflight(context.Context, *ProvisioningPreflightRequest) (*ProvisioningPreflightResponse, error)
	Find(context.Context, *FindRequest) (*FindResponse, error)
	TargetArchitecture(context.Context, *TargetArchitectureRequest) (*TargetArchitectureResponse, error)
	RunImage(context.Context, *RunImageRequest) (*RunImageResponse, error)
	Start(context.Context, *StartRequest) (*StartResponse, error)
	Stop(context.Context, *StopRequest) (*StopResponse, error)
	Delete(context.Context, *DeleteRequest) (*DeleteResponse, error)
	Exec(grpc.BidiStreamingServer[ExecClientMessage, ExecServerMessage]) error
	Logs(*LogsRequest, grpc.ServerStreamingServer[OutputChunk]) error
	mustEmbedUnimplementedRuntimeDriverServer()
}

// UnimplementedRuntimeDriverServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedRuntimeDriverServer struct{}

func (UnimplementedRuntimeDriverServer) Info(context.Context, *InfoRequest) (*InfoResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Info not implemented")
}
func (UnimplementedRuntimeDriverServer) Preflight(context.Context, *PreflightRequest) (*PreflightResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Preflight not implemented")
}
func (UnimplementedRuntimeDriverServer) ProvisioningPreflight(context.Context, *ProvisioningPreflightRequest) (*ProvisioningPreflightResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ProvisioningPreflight not implemented")
}
func (UnimplementedRuntimeDriverServer) Find(context.Context, *FindRequest) (*FindResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Find not implemented")
}
func (UnimplementedRuntimeDriverServer) TargetArchitecture(context.Context, *TargetArchitectureRequest) (*TargetArchitectureResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method TargetArchitecture not implemented")
}
func (UnimplementedRuntimeDriverServer) RunImage(context.Context, *RunImageRequest) (*RunImageResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method RunImage not implemented")
}
func (UnimplementedRuntimeDriverServer) Start(context.Context, *StartRequest) (*StartResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Start not implemented")
}
func (UnimplementedRuntimeDriverServer) Stop(context.Context, *StopRequest) (*StopResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Stop not implemented")
}
func (UnimplementedRuntimeDriverServer) Delete(context.Context, *DeleteRequest) (*DeleteResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Delete not implemented")
}
func (UnimplementedRuntimeDriverServer) Exec(grpc.BidiStreamingServer[ExecClientMessage, ExecServerMessage]) error {
	return status.Error(codes.Unimplemented, "method Exec not implemented")
}
func (UnimplementedRuntimeDriverServer) Logs(*LogsRequest, grpc.ServerStreamingServer[OutputChunk]) error {
	return status.Error(codes.Unimplemented, "method Logs not implemented")
}
func (UnimplementedRuntimeDriverServer) mustEmbedUnimplementedRuntimeDriverServer() {}
func (UnimplementedRuntimeDriverServer) testEmbeddedByValue()                       {}

// UnsafeRuntimeDriverServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to RuntimeDriverServer will
// result in compilation errors.
type UnsafeRuntimeDriverServer interface {
	mustEmbedUnimplementedRuntimeDriverServer()
}

func RegisterRuntimeDriverServer(s grpc.ServiceRegistrar, srv RuntimeDriverServer) {
	// If the following call panics, it indicates UnimplementedRuntimeDriverServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&RuntimeDriver_ServiceDesc, srv)
}

func _RuntimeDriver_Info_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(InfoRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RuntimeDriverServer).Info(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RuntimeDriver_Info_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RuntimeDriverServer).Info(ctx, req.(*InfoRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RuntimeDriver_Preflight_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PreflightRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RuntimeDriverServer).Preflight(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RuntimeDriver_Preflight_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RuntimeDriverServer).Preflight(ctx, req.(*PreflightRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RuntimeDriver_ProvisioningPreflight_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ProvisioningPreflightRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RuntimeDriverServer).ProvisioningPreflight(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RuntimeDriver_ProvisioningPreflight_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RuntimeDriverServer).ProvisioningPreflight(ctx, req.(*ProvisioningPreflightRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RuntimeDriver_Find_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FindRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RuntimeDriverServer).Find(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RuntimeDriver_Find_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RuntimeDriverServer).Find(ctx, req.(*FindRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RuntimeDriver_TargetArchitecture_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TargetArchitectureRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RuntimeDriverServer).TargetArchitecture(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RuntimeDriver_TargetArchitecture_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RuntimeDriverServer).TargetArchitecture(ctx, req.(*TargetArchitectureRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RuntimeDriver_RunImage_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RunImageRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RuntimeDriverServer).RunImage(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RuntimeDriver_RunImage_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RuntimeDriverServer).RunImage(ctx, req.(*RunImageRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RuntimeDriver_Start_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StartRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RuntimeDriverServer).Start(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RuntimeDriver_Start_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RuntimeDriverServer).Start(ctx, req.(*StartRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RuntimeDriver_Stop_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StopRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RuntimeDriverServer).Stop(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RuntimeDriver_Stop_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RuntimeDriverServer).Stop(ctx, req.(*StopRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RuntimeDriver_Delete_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RuntimeDriverServer).Delete(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RuntimeDriver_Delete_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RuntimeDriverServer).Delete(ctx, req.(*DeleteRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RuntimeDriver_Exec_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(RuntimeDriverServer).Exec(&grpc.GenericServerStream[ExecClientMessage, ExecServerMessage]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type RuntimeDriver_ExecServer = grpc.BidiStreamingServer[ExecClientMessage, ExecServerMessage]

func _RuntimeDriver_Logs_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(LogsRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(RuntimeDriverServer).Logs(m, &grpc.GenericServerStream[LogsRequest, OutputChunk]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type RuntimeDriver_LogsServer = grpc.ServerStreamingServer[OutputChunk]

// RuntimeDriver_ServiceDesc is the grpc.ServiceDesc for RuntimeDriver service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var RuntimeDriver_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "devsy.runtime.v1.RuntimeDriver",
	HandlerType: (*RuntimeDriverServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Info",
			Handler:    _RuntimeDriver_Info_Handler,
		},
		{
			MethodName: "Preflight",
			Handler:    _RuntimeDriver_Preflight_Handler,
		},
		{
			MethodName: "ProvisioningPreflight",
			Handler:    _RuntimeDriver_ProvisioningPreflight_Handler,
		},
		{
			MethodName: "Find",
			Handler:    _RuntimeDriver_Find_Handler,
		},
		{
			MethodName: "TargetArchitecture",
			Handler:    _RuntimeDriver_TargetArchitecture_Handler,
		},
		{
			MethodName: "RunImage",
			Handler:    _RuntimeDriver_RunImage_Handler,
		},
		{
			MethodName: "Start",
			Handler:    _RuntimeDriver_Start_Handler,
		},
		{
			MethodName: "Stop",
			Handler:    _RuntimeDriver_Stop_Handler,
		},
		{
			MethodName: "Delete",
			Handler:    _RuntimeDriver_Delete_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "Exec",
			Handler:       _RuntimeDriver_Exec_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
		{
			StreamName:    "Logs",
			Handler:       _RuntimeDriver_Logs_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "devsy/runtime/v1/runtime.proto",
}
