// Runtime Protocol v1. Field numbers are stable once released.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        v7.36.1
// source: devsy/runtime/v1/runtime.proto

package runtimev1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type MountType int32

const (
	MountType_MOUNT_TYPE_UNSPECIFIED MountType = 0
	MountType_MOUNT_TYPE_BIND        MountType = 1
	MountType_MOUNT_TYPE_VOLUME      MountType = 2
	MountType_MOUNT_TYPE_TMPFS       MountType = 3
)

// Enum value maps for MountType.
var (
	MountType_name = map[int32]string{
		0: "MOUNT_TYPE_UNSPECIFIED",
		1: "MOUNT_TYPE_BIND",
		2: "MOUNT_TYPE_VOLUME",
		3: "MOUNT_TYPE_TMPFS",
	}
	MountType_value = map[string]int32{
		"MOUNT_TYPE_UNSPECIFIED": 0,
		"MOUNT_TYPE_BIND":        1,
		"MOUNT_TYPE_VOLUME":      2,
		"MOUNT_TYPE_TMPFS":       3,
	}
)

func (x MountType) Enum() *MountType {
	p := new(MountType)
	*p = x
	return p
}

func (x MountType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (MountType) Descriptor() protoreflect.EnumDescriptor {
	return file_devsy_runtime_v1_runtime_proto_enumTypes[0].Descriptor()
}

func (MountType) Type() protoreflect.EnumType {
	return &file_devsy_runtime_v1_runtime_proto_enumTypes[0]
}

func (x MountType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use MountType.Descriptor instead.
func (MountType) EnumDescriptor() ([]byte, []int) {
	return file_devsy_runtime_v1_runtime_proto_rawDescGZIP(), []int{0}
}

type RecreateMode int32

const (
	RecreateMode_RECREATE_MODE_UNSPECIFIED RecreateMode = 0
	RecreateMode_RECREATE_MODE_DELETE      RecreateMode = 1
	RecreateMode_RECREATE_MODE_STOP        RecreateMode = 2
)

// Enum value maps for RecreateMode.
var (
	RecreateMode_name = map[int32]string{
		0: "RECREATE_MODE_UNSPECIFIED",
		1: "RECREATE_MODE_DELETE",
		2: "RECREATE_MODE_STOP",
	}
	RecreateMode_value = map[string]int32{
		"RECREATE_MODE_UNSPECIFIED": 0,
		"RECREATE_MODE_DELETE":      1,
		"RECREATE_MODE_STOP":        2,
	}
)

func (x RecreateMode) Enum() *RecreateMode {
	p := new(RecreateMode)
	*p = x
	return p
}

func (x RecreateMode) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (RecreateMode) Descriptor() protoreflect.EnumDescriptor {
	return file_devsy_runtime_v1_runtime_proto_enumTypes[1].Descriptor()
}

func (RecreateMode) Type() protoreflect.EnumType {
	return &file_devsy_runtime_v1_runtime_proto_enumTypes[1]
}

func (x RecreateMode) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use RecreateMode.Descriptor instead.
func (RecreateMode) EnumDescriptor() ([]byte, []int) {
	return file_devsy_runtime_v1_runtime_proto_rawDescGZIP(), []int{1}
}

type GpuRequirementValue int32

const (
	GpuRequirementValue_GPU_UNSPECIFIED GpuRequirementValue = 0
	GpuRequirementValue_GPU_FALSE       GpuRequirementValue = 1
	GpuRequirementValue_GPU_OPTIONAL    GpuRequirementValue = 2
	GpuRequirementValue_GPU_REQUIRED    GpuRequirementValue = 3
)

// Enum value maps for GpuRequirementValue.
var (
	GpuRequirementValue_name = map[int32]string{
		0: "GPU_UNSPECIFIED",
		1: "GPU_FALSE",
		2: "GPU_OPTIONAL",
		3: "GPU_REQUIRED",
	}
	GpuRequirementValue_value = map[string]int32{
		"GPU_UNSPECIFIED": 0,
		"GPU_FALSE":       1,
		"GPU_OPTIONAL":    2,
		"GPU_REQUIRED":    3,
	}
)

func (x GpuRequirementValue) Enum() *GpuRequirementValue {
	p := new(GpuRequirementValue)
	*p = x
	return p
}

func (x GpuRequirementValue) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (GpuRequirementValue) Descriptor() protoreflect.EnumDescriptor {
	return file_devsy_runtime_v1_runtime_proto_enumTypes[2].Descriptor()
}

func (GpuRequirementValue) Type() protoreflect.EnumType {
	return &file_devsy_runtime_v1_runtime_proto_enumTypes[2]
}

func (x GpuRequirementValue) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use GpuRequirementValue.Descriptor instead.
func (GpuRequirementValue) EnumDescriptor() ([]byte, []int) {
	return file_devsy_runtime_v1_runtime_proto_rawDescGZIP(), []int{2}
}

type RuntimeErrorCode int32

const (
	RuntimeErrorCode_RUNTIME_ERROR_CODE_UNKNOWN              RuntimeErrorCode = 0
	RuntimeErrorCode_RUNTIME_ERROR_CODE_NOT_FOUND            RuntimeErrorCode = 1
	RuntimeErrorCode_RUNTIME_ERROR_CODE_ALREADY_EXISTS       RuntimeErrorCode = 2
	RuntimeErrorCode_RUNTIME_ERROR_CODE_INVALID_ARGUMENT     RuntimeErrorCode = 3
	RuntimeErrorCode_RUNTIME_ERROR_CODE_UNSUPPORTED          RuntimeErrorCode = 4
	RuntimeErrorCode_RUNTIME_ERROR_CODE_UNAVAILABLE          RuntimeErrorCode = 5
	RuntimeErrorCode_RUNTIME_ERROR_CODE_FAILED_PRECONDITION  RuntimeErrorCode = 6
	RuntimeErrorCode_RUNTIME_ERROR_CODE_PERMISSION_DENIED    RuntimeErrorCode = 7
	RuntimeErrorCode_RUNTIME_ERROR_CODE_TIMEOUT              RuntimeErrorCode = 8
	RuntimeErrorCode_RUNTIME_ERROR_CODE_CANCELLED            RuntimeErrorCode = 9
	RuntimeErrorCode_RUNTIME_ERROR_CODE_RUNTIME_FAILURE      RuntimeErrorCode = 10
	RuntimeErrorCode_RUNTIME_ERROR_CODE_INCOMPATIBLE_VERSION RuntimeErrorCode = 11
)

// Enum value maps for RuntimeErrorCode.
var (
	RuntimeErrorCode_name = map[int32]string{
		0:  "RUNTIME_ERROR_CODE_UNKNOWN",
		1:  "RUNTIME_ERROR_CODE_NOT_FOUND",
		2:  "RUNTIME_ERROR_CODE_ALREADY_EXISTS",
		3:  "RUNTIME_ERROR_CODE_INVALID_ARGUMENT",
		4:  "RUNTIME_ERROR_CODE_UNSUPPORTED",
		5:  "RUNTIME_ERROR_CODE_UNAVAILABLE",
		6:  "RUNTIME_ERROR_CODE_FAILED_PRECONDITION",
		7:  "RUNTIME_ERROR_CODE_PERMISSION_DENIED",
		8:  "RUNTIME_ERROR_CODE_TIMEOUT",
		9:  "RUNTIME_ERROR_CODE_CANCELLED",
		10: "RUNTIME_ERROR_CODE_RUNTIME_FAILURE",
		11: "RUNTIME_ERROR_CODE_INCOMPATIBLE_VERSION",
	}
	RuntimeErrorCode_value = map[string]int32{
		"RUNTIME_ERROR_CODE_UNKNOWN":              0,
		"RUNTIME_ERROR_CODE_NOT_FOUND":            1,
		"RUNTIME_ERROR_CODE_ALREADY_EXISTS":       2,
		"RUNTIME_ERROR_CODE_INVALID_ARGUMENT":     3,
		"RUNTIME_ERROR_CODE_UNSUPPORTED":          4,
		"RUNTIME_ERROR_CODE_UNAVAILABLE":          5,
		"RUNTIME_ERROR_CODE_FAILED_PRECONDITION":  6,
		"RUNTIME_ERROR_CODE_PERMISSION_DENIED":    7,
		"RUNTIME_ERROR_CODE_TIMEOUT":              8,
		"RUNTIME_ERROR_CODE_CANCELLED":            9,
		"RUNTIME_ERROR_CODE_RUNTIME_FAILURE":      10,
		"RUNTIME_ERROR_CODE_INCOMPATIBLE_VERSION": 11,
	}
)

func (x RuntimeErrorCode) Enum() *RuntimeErrorCode {
	p := new(RuntimeErrorCode)
	*p = x
	return p
}

func (x RuntimeErrorCode) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (RuntimeErrorCode) Descriptor() protoreflect.EnumDescriptor {
	return file_devsy_runtime_v1_runtime_proto_enumTypes[3].Descriptor()
}

func (RuntimeErrorCode) Type() protoreflect.EnumType {
	return &file_devsy_runtime_v1_runtime_proto_enumTypes[3]
}

func (x RuntimeErrorCode) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use RuntimeErrorCode.Descriptor instead.
func (RuntimeErrorCode) EnumDescriptor() ([]byte, []int) {
	return file_devsy_runtime_v1_runtime_proto_rawDescGZIP(), []int{3}
}

type InfoRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InfoRequest) Reset() {
	*x = InfoRequest{}
	mi := &file_devsy_runtime_v1_runtime_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InfoRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InfoRequest) ProtoMessage() {}

func (x *InfoRequest) ProtoReflect() protoreflect.Message {
	mi := &file_devsy_runtime_v1_runtime_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InfoRequest.ProtoReflect.Descriptor instead.
func (*InfoRequest) Descriptor() ([]byte, []int) {
	return file_devsy_runtime_v1_runtime_proto_rawDescGZIP(), []int{0}
}

type InfoResponse struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	ApiMajor       uint32                 `protobuf:"varint,1,opt,name=api_major,json=apiMajor,proto3" json:"api_major,omitempty"`
	ApiMinor       uint32                 `protobuf:"varint,2,opt,name=api_minor,json=apiMinor,proto3" json:"api_minor,omitempty"`
	DriverName     string                 `protobuf:"bytes,3,opt,name=driver_name,json=driverName,proto3" json:"driver_name,omitempty"`
	DriverVersion  string                 `protobuf:"bytes,4,opt,name=driver_version,json=driverVersion,proto3" json:"driver_version,omitempty"`
	RuntimeName    string                 `protobuf:"bytes,5,opt,name=runtime_name,json=runtimeName,proto3" json:"runtime_name,omitempty"`
	RuntimeVersion string                 `protobuf:"bytes,6,opt,name=runtime_version,json=runtimeVersion,proto3" json:"runtime_version,omitempty"`
	Capabilities   *Capabilities          `protobuf:"bytes,7,opt,name=capabilities,proto3" json:"capabilities,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *InfoResponse) Reset() {
	*x = InfoResponse{}
	mi := &file_devsy_runtime_v1_runtime_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InfoResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InfoResponse) ProtoMessage() {}

func (x *InfoResponse) ProtoReflect() protoreflect.Message {
	mi := &file_devsy_runtime_v1_runtime_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InfoResponse.ProtoReflect.Descriptor instead.
func (*InfoResponse) Descriptor() ([]byte, []int) {
	return file_devsy_runtime_v1_runtime_proto_rawDescGZIP(), []int{1}
}

func (x *InfoResponse) GetApiMajor() uint32 {
	if x != nil {
		return x.ApiMajor
	}
	return 0
}

func (x *InfoResponse) GetApiMinor() uint32 {
	if x != nil {
		return x.ApiMinor
	}
	return 0
}

func (x *InfoResponse) GetDriverName() string {
	if x != nil {
		return x.DriverName
	}
	return ""
}

func (x *InfoResponse) GetDriverVersion() string {
	if x != nil {
		return x.DriverVersion
	}
	return ""
}

func (x *InfoResponse) GetRuntimeName() string {
	if x != nil {
		return x.RuntimeName
	}
	return ""
}

func (x *InfoResponse) GetRuntimeVersion() string {
	if x != nil {
		return x.RuntimeVersion
	}
	return ""
}

func (x *InfoResponse) GetCapabilities() *Capabilities {
	if x != nil {
		return x.Capabilities
	}
	return nil
}

type Capabilities struct {
	state                  protoimpl.MessageState `protogen:"open.v1"`
	MountTypes             []MountType            `protobuf:"varint,1,rep,packed,name=mount_types,json=mountTypes,proto3,enum=devsy.runtime.v1.MountType" json:"mount_types,omitempty"`
	RequiresMountStreaming bool                   `protobuf:"varint,2,opt,name=requires_mount_streaming,json=requiresMountStreaming,proto3" json:"requires_mount_streaming,omitempty"`
	RequiresWorkspaceChown bool                   `protobuf:"varint,3,opt,name=requires_workspace_chown,json=requiresWorkspaceChown,proto3" json:"requires_workspace_chown,omitempty"`
	RecreateMode           RecreateMode           `protobuf:"varint,4,opt,name=recreate_mode,json=recreateMode,proto3,enum=devsy.runtime.v1.RecreateMode" json:"recreate_mode,omitempty"`
	ProvisioningPreflight  bool                   `protobuf:"varint,5,opt,name=provisioning_preflight,json=provisioningPreflight,proto3" json:"provisioning_preflight,omitempty"`
	Reprovision            bool                   `protobuf:"varint,6,opt,name=reprovision,proto3" json:"reprovision,omitempty"`
	Logs                   bool                   `protobuf:"varint,7,opt,name=logs,proto3" json:"logs,omitempty"`
	// Validate an existing workspace's creation-time contract without mutation.
	ReusePreflight bool `protobuf:"varint,8,opt,name=reuse_preflight,json=reusePreflight,proto3" json:"reuse_preflight,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *Capabilities) Reset() {
	*x = Capabilities{}
	mi := &file_devsy_runtime_v1_runtime_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Capabilities) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Capabilities) ProtoMessage() {}

func (x *Capabilities) ProtoReflect() protoreflect.Message {
	mi := &file_devsy_runtime_v1_runtime_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Capabilities.ProtoReflect.Descriptor instead.
func (*Capabilities) Descriptor() ([]byte, []int) {
	return file_devsy_runtime_v1_runtime_proto_rawDescGZIP(), []int{2}
}

func (x *Capabilities) GetMountTypes() []MountType {
	if x != nil {
		return x.MountTypes
	}
	return nil
}

func (x *Capabilities) GetRequiresMountStreaming() bool {
	if x != nil {
		return x.RequiresMountStreaming
	}
	return false
}

func (x *Capabilities) GetRequiresWorkspaceChown() bool {
	if x != nil {
		return x.RequiresWorkspaceChown
	}
	return false
}

func (x *Capabilities) GetRecreateMode() RecreateMode {
	if x != nil {
		return x.RecreateMode
	}
	return RecreateMode_RECREATE_MODE_UNSPECIFIED
}

func (x *Capabilities) GetProvisioningPreflight() bool {
	if x != nil {
		return x.ProvisioningPreflight
	}
	return false
}

func (x *Capabilities) GetReprovision() bool {
	if x != nil {
		return x.Reprovision
	}
	return false
}

func (x *Capabilities) GetLogs() bool {
	if x != nil {
		return x.Logs
	}
	return false
}

func (x *Capabilities) GetReusePreflight() bool {
	if x != nil {
		return x.ReusePreflight
	}
	return false
}

type PreflightRequest struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	DisableAutoStart bool                   `protobuf:"varint,1,opt,name=disable_auto_start,json=disableAutoStart,proto3" json:"disable_auto_start,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *PreflightRequest) Reset() {
	*x = PreflightRequest{}
	mi := &file_devsy_runtime_v1_runtime_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PreflightRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PreflightRequest) ProtoMessage() {}

func (x *PreflightRequest) ProtoReflect() protoreflect.Message {
	mi := &file_devsy_runtime_v1_runtime_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PreflightRequest.ProtoReflect.Descriptor instead.
func (*PreflightRequest) Descriptor() ([]byte, []int) {
	return file_devsy_runtime_v1_runtime_proto_rawDescGZIP(), []int{3}
}

func (x *PreflightRequest) GetDisableAutoStart() bool {
	if x != nil {
		return x.DisableAutoStart
	}
	return false
}

type PreflightResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PreflightResponse) Reset() {
	*x = PreflightResponse{}
	mi := &file_devsy_runtime_v1_runtime_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PreflightResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PreflightResponse) ProtoMessage() {}

func (x *PreflightResponse) ProtoReflect() protoreflect.Message {
	mi := &file_devsy_runtime_v1_runtime_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PreflightResponse.ProtoReflect.Descriptor instead.
func (*PreflightResponse) Descriptor() ([]byte, []int) {
	return file_devsy_runtime_v1_runtime_proto_rawDescGZIP(), []int{4}
}

type ProvisioningPreflightRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProvisioningPreflightRequest) Reset() {
	*x = ProvisioningPreflightRequest{}
	mi := &file_devsy_runtime_v1_runtime_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProvisioningPreflightRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProvisioningPreflightRequest) ProtoMessage() {}

func (x *ProvisioningPreflightRequest) ProtoReflect() protoreflect.Message {
	mi := &file_devsy_runtime_v1_runtime_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProvisioningPreflightRequest.ProtoReflect.Descriptor instead.
func (*ProvisioningPreflightRequest) Descriptor() ([]byte, []int) {
	return file_devsy_runtime_v1_runtime_proto_rawDescGZIP(), []int{5}
}

type ProvisioningPreflightResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProvisioningPreflightResponse) Reset() {
	*x = ProvisioningPreflightResponse{}
	mi := &file_devsy_runtime_v1_runtime_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProvisioningPreflightResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProvisioningPreflightResponse) ProtoMessage() {}

func (x *ProvisioningPreflightResponse) ProtoReflect() protoreflect.Message {
	mi := &file_devsy_runtime_v1_runtime_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProvisioningPreflightResponse.ProtoReflect.Descriptor instead.
func (*ProvisioningPreflightResponse) Descriptor() ([]byte, []int) {
	return file_devsy_runtime_v1_runtime_proto_rawDescGZIP(), []int{6}
}

type ReusePreflightRequest struct {
	state       protoimpl.MessageState `protogen:"open.v1"`
	WorkspaceId string                 `protobuf:"bytes,1,opt,name=workspace_id,json=workspaceId,proto3" json:"workspace_id,omitempty"`
	// Resolved, nonempty developer identity for the requested reuse.
	RemoteUser    string `protobuf:"bytes,2,opt,name=remote_user,json=remoteUser,proto3" json:"remote_user,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReusePreflightRequest) Reset() {
	*x = ReusePreflightRequest{}
	mi := &file_devsy_runtime_v1_runtime_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReusePreflightRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReusePreflightRequest) ProtoMessage() {}

func (x *ReusePreflightRequest) ProtoReflect() protoreflect.Message {
	mi := &file_devsy_runtime_v1_runtime_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReusePreflightRequest.ProtoReflect.Descriptor instead.
func (*ReusePreflightRequest) Descriptor() ([]byte, []int) {
	return file_devsy_runtime_v1_runtime_proto_rawDescGZIP(), []int{7}
}

func (x *ReusePreflightRequest) GetWorkspaceId() string {
	if x != nil {
		return x.WorkspaceId
	}
	return ""
}

func (x *ReusePreflightRequest) GetRemoteUser() string {
	if x != nil {
		return x.RemoteUser
	}
	return ""
}

type ReusePreflightResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReusePreflightResponse) Reset() {
	*x = ReusePreflightResponse{}
	mi := &file_devsy_runtime_v1_runtime_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReusePreflightResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReusePreflightResponse) ProtoMessage() {}

func (x *ReusePreflightResponse) ProtoReflect() protoreflect.Message {
	mi := &file_devsy_runtime_v1_runtime_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReusePreflightResponse.ProtoReflect.Descriptor instead.
func (*ReusePreflightResponse) Descriptor() ([]byte, []int) {
	return file_devsy_runtime_v1_runtime_proto_rawDescGZIP(), []int{8}
}

type FindRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	WorkspaceId   string                 `protobuf:"bytes,1,opt,name=workspace_id,json=workspaceId,proto3" json:"workspace_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FindRequest) Reset() {
	*x = FindRequest{}
	mi := &file_devsy_runtime_v1_runtime_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FindRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FindRequest) ProtoMessage() {}

func (x *FindRequest) ProtoReflect() protoreflect.Message {
	mi := &file_devsy_runtime_v1_runtime_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FindRequest.ProtoReflect.Descriptor instead.
func (*FindRequest) Descriptor() ([]byte, []int) {
	return file_devsy_runtime_v1_runtime_proto_rawDescGZIP(), []int{9}
}

func (x *FindRequest) GetWorkspaceId() string {
	if x != nil {
		return x.WorkspaceId
	}
	return ""
}

type FindResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Found         bool                   `protobuf:"varint,1,opt,name=found,proto3" json:"found,omitempty"`
	Container     *ContainerDetails      `protobuf:"bytes,2,opt,name=container,proto3" json:"container,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FindResponse) Reset() {
	*x = FindResponse{}
	mi := &file_devsy_runtime_v1_runtime_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FindResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FindResponse) ProtoMessage() {}

func (x *FindResponse) ProtoReflect() protoreflect.Message {
	mi := &file_devsy_runtime_v1_runtime_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FindResponse.ProtoReflect.Descriptor instead.
func (*FindResponse) Descriptor() ([]byte, []int) {
	return file_devsy_runtime_v1_runtime_proto_rawDescGZIP(), []int{10}
}

func (x *FindResponse) GetFound() bool {
	if x != nil {
		return x.Found
	}
	return false
}

func (x *FindResponse) GetContainer() *ContainerDetails {
	if x != nil {
		return x.Container
	}
	return nil
}

type ContainerDetails struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	CreatedAt     string                 `protobuf:"bytes,2,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	State         *ContainerState        `protobuf:"bytes,3,opt,name=state,proto3" json:"state,omitempty"`
	Config        *ContainerConfig       `protobuf:"bytes,4,opt,name=config,proto3" json:"config,omitempty"`
	Mounts        []*ContainerMount      `protobuf:"bytes,5,rep,name=mounts,proto3" json:"mounts,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ContainerDetails) Reset() {
	*x = ContainerDetails{}
	mi := &file_devsy_runtime_v1_runtime_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ContainerDetails) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ContainerDetails) ProtoMessage() {}

func (x *ContainerDetails) ProtoReflect() protoreflect.Message {
	mi := &file_devsy_runtime_v1_runtime_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ContainerDetails.ProtoReflect.Descriptor instead.
func (*ContainerDetails) Descriptor() ([]byte, []int) {
	return file_devsy_runtime_v1_runtime_proto_rawDescGZIP(), []int{11}
}

func (x *ContainerDetails) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *ContainerDetails) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

func (x *ContainerDetails) GetState() *ContainerState {
	if x != nil {
		return x.State
	}
	return nil
}

func (x *ContainerDetails) GetConfig() *ContainerConfig {
	if x != nil {
		return x.Config
	}
	return nil
}

func (x *ContainerDetails) GetMounts() []*ContainerMount {
	if x != nil {
		return x.Mounts
	}
	return nil
}

type ContainerState struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        string                 `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	StartedAt     string                 `protobuf:"bytes,2,opt,name=started_at,json=startedAt,proto3" json:"started_at,omitempty"`
	ExitCode      int32                  `protobuf:"varint,3,opt,name=exit_code,json=exitCode,proto3" json:"exit_code,omitempty"`
	Error         string                 `protobuf:"bytes,4,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ContainerState) Reset() {
	*x = ContainerState{}
	mi := &file_devsy_runtime_v1_runtime_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ContainerState) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ContainerState) ProtoMessage() {}

func (x *ContainerState) ProtoReflect() protoreflect.Message {
	mi := &file_devsy_runtime_v1_runtime_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ContainerState.ProtoReflect.Descriptor instead.
func (*ContainerState) Descriptor() ([]byte, []int) {
	return file_devsy_runtime_v1_runtime_proto_rawDescGZIP(), []int{12}
}

func (x *ContainerState) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *ContainerState) GetStartedAt() string {
	if x != nil {
		return x.StartedAt
	}
	return ""
}

func (x *ContainerState) GetExitCode() int32 {
	if x != nil {
		return x.ExitCode
	}
	return 0
}

func (x *ContainerState) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type ContainerConfig struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Labels        map[string]string      `protobuf:"bytes,1,rep,name=labels,proto3" json:"labels,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	WorkingDir    string                 `protobuf:"bytes,2,opt,name=working_dir,json=workingDir,proto3" json:"working_dir,omitempty"`
	User          string                 `protobuf:"bytes,3,opt,name=user,proto3" json:"user,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ContainerConfig) Reset() {
	*x = ContainerConfig{}
	mi := &file_devsy_runtime_v1_runtime_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ContainerConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ContainerConfig) ProtoMessage() {}

func (x *ContainerConfig) ProtoReflect() protoreflect.Message {
	mi := &file_devsy_runtime_v1_runtime_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ContainerConfig.ProtoReflect.Descriptor instead.
func (*ContainerConfig) Descriptor() ([]byte, []int) {
	return file_devsy_runtime_v1_runtime_proto_rawDescGZIP(), []int{13}
}

func (x *ContainerConfig) GetLabels() map[string]string {
	if x != nil {
		return x.Labels
	}
	return nil
}

func (x *ContainerConfig) GetWorkingDir() string {
	if x != nil {
		return x.WorkingDir
	}
	return ""
}

func (x *ContainerConfig) GetUser() string {
	if x != nil {
		return x.User
	}
	return ""
}

type ContainerMount struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Type          string                 `protobuf:"bytes,1,opt,name=type,proto3" json:"type,omitempty"`
	Source        string                 `protobuf:"bytes,2,opt,name=source,proto3" json:"source,omitempty"`
	Destination   string                 `protobuf:"bytes,3,opt,name=destination,proto3" json:"destination,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ContainerMount) Reset() {
	*x = ContainerMount{}
	mi := &file_devsy_runtime_v1_runtime_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ContainerMount) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ContainerMount) ProtoMessage() {}

func (x *ContainerMount) ProtoReflect() protoreflect.Message {
	mi := &file_devsy_runtime_v1_runtime_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ContainerMount.ProtoReflect.Descriptor instead.
func (*ContainerMount) Descriptor() ([]byte, []int) {
	return file_devsy_runtime_v1_runtime_proto_rawDescGZIP(), []int{14}
}

func (x *ContainerMount) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *ContainerMount) GetSource() string {
	if x != nil {
		return x.Source
	}
	return ""
}

func (x *ContainerMount) GetDestination() string {
	if x != nil {
		return x.Destination
	}
	return ""
}

type TargetArchitectureRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	WorkspaceId   string                 `protobuf:"bytes,1,opt,name=workspace_id,json=workspaceId,proto3" json:"workspace_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TargetArchitectureRequest) Reset() {
	*x = TargetArchitectureRequest{}
	mi := &file_devsy_runtime_v1_runtime_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TargetArchitectureRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TargetArchitectureRequest) ProtoMessage() {}

func (x *TargetArchitectureRequest) ProtoReflect() protoreflect.Message {
	mi := &file_devsy_runtime_v1_runtime_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TargetArchitectureRequest.ProtoReflect.Descriptor instead.
func (*TargetArchitectureRequest) Descriptor() ([]byte, []int) {
	return file_devsy_runtime_v1_runtime_proto_rawDescGZIP(), []int{15}
}

func (x *TargetArchitectureRequest) GetWorkspaceId() string {
	if x != nil {
		return x.WorkspaceId
	}
	return ""
}

type TargetArchitectureResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Architecture  string                 `protobuf:"bytes,1,opt,name=architecture,proto3" json:"architecture,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TargetArchitectureResponse) Reset() {
	*x = TargetArchitectureResponse{}
	mi := &file_devsy_runtime_v1_runtime_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TargetArchitectureResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TargetArchitectureResponse) ProtoMessage() {}

func (x *TargetArchitectureResponse) ProtoReflect() protoreflect.Message {
	mi := &file_devsy_runtime_v1_runtime_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TargetArchitectureResponse.ProtoReflect.Descriptor instead.
func (*TargetArchitectureResponse) Descriptor() ([]byte, []int) {
	return file_devsy_runtime_v1_runtime_proto_rawDescGZIP(), []int{16}
}

func (x *TargetArchitectureResponse) GetArchitecture() string {
	if x != nil {
		return x.Architecture
	}
	return ""
}

type RunImageRequest struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	WorkspaceId       string                 `protobuf:"bytes,1,opt,name=workspace_id,json=workspaceId,proto3" json:"workspace_id,omitempty"`
	Image             string                 `protobuf:"bytes,2,opt,name=image,proto3" json:"image,omitempty"`
	ImageBuiltLocally bool                   `protobuf:"varint,3,opt,name=image_built_locally,json=imageBuiltLocally,proto3" json:"image_built_locally,omitempty"`
	User              string                 `protobuf:"bytes,4,opt,name=user,proto3" json:"user,omitempty"`
	Entrypoint        string                 `protobuf:"bytes,5,opt,name=entrypoint,proto3" json:"entrypoint,omitempty"`
	Args              []string               `protobuf:"bytes,6,rep,name=args,proto3" json:"args,omitempty"`
	Environment       map[string]string      `protobuf:"bytes,7,rep,name=environment,proto3" json:"environment,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	Labels            []string               `protobuf:"bytes,8,rep,name=labels,proto3" json:"labels,omitempty"`
	CapAdd            []string               `protobuf:"bytes,9,rep,name=cap_add,json=capAdd,proto3" json:"cap_add,omitempty"`
	SecurityOpt       []string               `protobuf:"bytes,10,rep,name=security_opt,json=securityOpt,proto3" json:"security_opt,omitempty"`
	Privileged        *bool                  `protobuf:"varint,11,opt,name=privileged,proto3,oneof" json:"privileged,omitempty"`
	Init              *bool                  `protobuf:"varint,12,opt,name=init,proto3,oneof" json:"init,omitempty"`
	WorkspaceMount    *Mount                 `protobuf:"bytes,13,opt,name=workspace_mount,json=workspaceMount,proto3" json:"workspace_mount,omitempty"`
	Mounts            []*Mount               `protobuf:"bytes,14,rep,name=mounts,proto3" json:"mounts,omitempty"`
	Userns            string                 `protobuf:"bytes,15,opt,name=userns,proto3" json:"userns,omitempty"`
	UidMap            []string               `protobuf:"bytes,16,rep,name=uid_map,json=uidMap,proto3" json:"uid_map,omitempty"`
	GidMap            []string               `protobuf:"bytes,17,rep,name=gid_map,json=gidMap,proto3" json:"gid_map,omitempty"`
	Platform          string                 `protobuf:"bytes,18,opt,name=platform,proto3" json:"platform,omitempty"`
	HostRequirements  *HostRequirements      `protobuf:"bytes,19,opt,name=host_requirements,json=hostRequirements,proto3" json:"host_requirements,omitempty"`
	// Developer identity for workspace ownership, distinct from the container user.
	// When empty, use user if set, otherwise root.
	RemoteUser string `protobuf:"bytes,20,opt,name=remote_user,json=remoteUser,proto3" json:"remote_user,omitempty"`
	// The host will provision the developer environment after starting this image.
	// Runtimes must not assume the final developer identity exists in the image.
	Dockerless    bool `protobuf:"varint,21,opt,name=dockerless,proto3" json:"dockerless,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RunImageRequest) Reset() {
	*x = RunImageRequest{}
	mi := &file_devsy_runtime_v1_runtime_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RunImageRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RunImageRequest) ProtoMessage() {}

func (x *RunImageRequest) ProtoReflect() protoreflect.Message {
	mi := &file_devsy_runtime_v1_runtime_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RunImageRequest.ProtoReflect.Descriptor instead.
func (*RunImageRequest) Descriptor() ([]byte, []int) {
	return file_devsy_runtime_v1_runtime_proto_rawDescGZIP(), []int{17}
}

func (x *RunImageRequest) GetWorkspaceId() string {
	if x != nil {
		return x.WorkspaceId
	}
	return ""
}

func (x *RunImageRequest) GetImage() string {
	if x != nil {
		return x.Image
	}
	return ""
}

func (x *RunImageRequest) GetImageBuiltLocally() bool {
	if x != nil {
		return x.ImageBuiltLocally
	}
	return false
}

func (x *RunImageRequest) GetUser() string {
	if x != nil {
		return x.User
	}
	return ""
}

func (x *RunImageRequest) GetEntrypoint() string {
	if x != nil {
		return x.Entrypoint
	}
	return ""
}

func (x *RunImageRequest) GetArgs() []string {
	if x != nil {
		return x.Args
	}
	return nil
}

func (x *RunImageRequest) GetEnvironment() map[string]string {
	if x != nil {
		return x.Environment
	}
	return nil
}

func (x *RunImageRequest) GetLabels() []string {
	if x != nil {
		return x.Labels
	}
	return nil
}

func (x *RunImageRequest) GetCapAdd() []string {
	if x != nil {
		return x.CapAdd
	}
	return nil
}

func (x *RunImageRequest) GetSecurityOpt() []string {
	if x != nil {
		return x.SecurityOpt
	}
	return nil
}

func (x *RunImageRequest) GetPrivileged() bool {
	if x != nil && x.Privileged != nil {
		return *x.Privileged
	}
	return false
}

func (x *RunImageRequest) GetInit() bool {
	if x != nil && x.Init != nil {
		return *x.Init
	}
	return false
}

func (x *RunImageRequest) GetWorkspaceMount() *Mount {
	if x != nil {
		return x.WorkspaceMount
	}
	return nil
}

func (x *RunImageRequest) GetMounts() []*Mount {
	if x != nil {
		return x.Mounts
	}
	return nil
}

func (x *RunImageRequest) GetUserns() string {
	if x != nil {
		return x.Userns
	}
	return ""
}

func (x *RunImageRequest) GetUidMap() []string {
	if x != nil {
		return x.UidMap
	}
	return nil
}

func (x *RunImageRequest) GetGidMap() []string {
	if x != nil {
		return x.GidMap
	}
	return nil
}

func (x *RunImageRequest) GetPlatform() string {
	if x != nil {
		return x.Platform
	}
	return ""
}

func (x *RunImageRequest) GetHostRequirements() *HostRequirements {
	if x != nil {
		return x.HostRequirements
	}
	return nil
}

func (x *RunImageRequest) GetRemoteUser() string {
	if x != nil {
		return x.RemoteUser
	}
	return ""
}

func (x *RunImageRequest) GetDockerless() bool {
	if x != nil {
		return x.Dockerless
	}
	return false
}

type Mount struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Type          MountType              `protobuf:"varint,1,opt,name=type,proto3,enum=devsy.runtime.v1.MountType" json:"type,omitempty"`
	Source        string                 `protobuf:"bytes,2,opt,name=source,proto3" json:"source,omitempty"`
	Target        string                 `protobuf:"bytes,3,opt,name=target,proto3" json:"target,omitempty"`
	ReadOnly      bool                   `protobuf:"varint,4,opt,name=read_only,json=readOnly,proto3" json:"read_only,omitempty"`
	Options       []string               `protobuf:"bytes,5,rep,name=options,proto3" json:"options,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Mount) Reset() {
	*x = Mount{}
	mi := &file_devsy_runtime_v1_runtime_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Mount) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Mount) ProtoMessage() {}

func (x *Mount) ProtoReflect() protoreflect.Message {
	mi := &file_devsy_runtime_v1_runtime_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Mount.ProtoReflect.Descriptor instead.
func (*Mount) Descriptor() ([]byte, []int) {
	return file_devsy_runtime_v1_runtime_proto_rawDescGZIP(), []int{18}
}

func (x *Mount) GetType() MountType {
	if x != nil {
		return x.Type
	}
	return MountType_MOUNT_TYPE_UNSPECIFIED
}

func (x *Mount) GetSource() string {
	if x != nil {
		return x.Source
	}
	return ""
}

func (x *Mount) GetTarget() string {
	if x != nil {
		return x.Target
	}
	return ""
}

func (x *Mount) GetReadOnly() bool {
	if x != nil {
		return x.ReadOnly
	}
	return false
}

func (x *Mount) GetOptions() []string {
	if x != nil {
		return x.Options
	}
	return nil
}

type HostRequirements struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Cpus          int32                  `protobuf:"varint,1,opt,name=cpus,proto3" json:"cpus,omitempty"`
	MemoryBytes   uint64                 `protobuf:"varint,2,opt,name=memory_bytes,json=memoryBytes,proto3" json:"memory_bytes,omitempty"`
	StorageBytes  uint64                 `protobuf:"varint,3,opt,name=storage_bytes,json=storageBytes,proto3" json:"storage_bytes,omitempty"`
	Gpu           *GpuRequirement        `protobuf:"bytes,4,opt,name=gpu,proto3" json:"gpu,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HostRequirements) Reset() {
	*x = HostRequirements{}
	mi := &file_devsy_runtime_v1_runtime_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HostRequirements) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HostRequirements) ProtoMessage() {}

func (x *HostRequirements) ProtoReflect() protoreflect.Message {
	mi := &file_devsy_runtime_v1_runtime_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HostRequirements.ProtoReflect.Descriptor instead.
func (*HostRequirements) Descriptor() ([]byte, []int) {
	return file_devsy_runtime_v1_runtime_proto_rawDescGZIP(), []int{19}
}

func (x *HostRequirements) GetCpus() int32 {
	if x != nil {
		return x.Cpus
	}
	return 0
}

func (x *HostRequirements) GetMemoryBytes() uint64 {
	if x != nil {
		return x.MemoryBytes
	}
	return 0
}

func (x *HostRequirements) GetStorageBytes() uint64 {
	if x != nil {
		return x.StorageBytes
	}
	return 0
}

func (x *HostRequirements) GetGpu() *GpuRequirement {
	if x != nil {
		return x.Gpu
	}
	return nil
}

type GpuRequirement struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Value         GpuRequirementValue    `protobuf:"varint,1,opt,name=value,proto3,enum=devsy.runtime.v1.GpuRequirementValue" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GpuRequirement) Reset() {
	*x = GpuRequirement{}
	mi := &file_devsy_runtime_v1_runtime_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GpuRequirement) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GpuRequirement) ProtoMessage() {}

func (x *GpuRequirement) ProtoReflect() protoreflect.Message {
	mi := &file_devsy_runtime_v1_runtime_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GpuRequirement.ProtoReflect.Descriptor instead.
func (*GpuRequirement) Descriptor() ([]byte, []int) {
	return file_devsy_runtime_v1_runtime_proto_rawDescGZIP(), []int{20}
}

func (x *GpuRequirement) GetValue() GpuRequirementValue {
	if x != nil {
		return x.Value
	}
	return GpuRequirementValue_GPU_UNSPECIFIED
}

type StartRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	WorkspaceId   string                 `protobuf:"bytes,1,opt,name=workspace_id,json=workspaceId,proto3" json:"workspace_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StartRequest) Reset() {
	*x = StartRequest{}
	mi := &file_devsy_runtime_v1_runtime_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StartRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StartRequest) ProtoMessage() {}

func (x *StartRequest) ProtoReflect() protoreflect.Message {
	mi := &file_devsy_runtime_v1_runtime_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StartRequest.ProtoReflect.Descriptor instead.
func (*StartRequest) Descriptor() ([]byte, []int) {
	return file_devsy_runtime_v1_runtime_proto_rawDescGZIP(), []int{21}
}

func (x *StartRequest) GetWorkspaceId() string {
	if x != nil {
		return x.WorkspaceId
	}
	return ""
}

type StartResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StartResponse) Reset() {
	*x = StartResponse{}
	mi := &file_devsy_runtime_v1_runtime_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StartResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StartResponse) ProtoMessage() {}

func (x *StartResponse) ProtoReflect() protoreflect.Message {
	mi := &file_devsy_runtime_v1_runtime_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StartResponse.ProtoReflect.Descriptor instead.
func (*StartResponse) Descriptor() ([]byte, []int) {
	return file_devsy_runtime_v1_runtime_proto_rawDescGZIP(), []int{22}
}

type StopRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	WorkspaceId   string                 `protobuf:"bytes,1,opt,name=workspace_id,json=workspaceId,proto3" json:"workspace_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StopRequest) Reset() {
	*x = StopRequest{}
	mi := &file_devsy_runtime_v1_runtime_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StopRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StopRequest) ProtoMessage() {}

func (x *StopRequest) ProtoReflect() protoreflect.Message {
	mi := &file_devsy_runtime_v1_runtime_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StopRequest.ProtoReflect.Descriptor instead.
func (*StopRequest) Descriptor() ([]byte, []int) {
	return file_devsy_runtime_v1_runtime_proto_rawDescGZIP(), []int{23}
}

func (x *StopRequest) GetWorkspaceId() string {
	if x != nil {
		return x.WorkspaceId
	}
	return ""
}

type StopResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StopResponse) Reset() {
	*x = StopResponse{}
	mi := &file_devsy_runtime_v1_runtime_proto_msgTypes[24]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StopResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StopResponse) ProtoMessage() {}

func (x *StopResponse) ProtoReflect() protoreflect.Message {
	mi := &file_devsy_runtime_v1_runtime_proto_msgTypes[24]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StopResponse.ProtoReflect.Descriptor instead.
func (*StopResponse) Descriptor() ([]byte, []int) {
	return file_devsy_runtime_v1_runtime_proto_rawDescGZIP(), []int{24}
}

type DeleteRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	WorkspaceId   string                 `protobuf:"bytes,1,opt,name=workspace_id,json=workspaceId,proto3" json:"workspace_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteRequest) Reset() {
	*x = DeleteRequest{}
	mi := &file_devsy_runtime_v1_runtime_proto_msgTypes[25]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteRequest) ProtoMessage() {}

func (x *DeleteRequest) ProtoReflect() protoreflect.Message {
	mi := &file_devsy_runtime_v1_runtime_proto_msgTypes[25]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteRequest.ProtoReflect.Descriptor instead.
func (*DeleteRequest) Descriptor() ([]byte, []int) {
	return file_devsy_runtime_v1_runtime_proto_rawDescGZIP(), []int{25}
}

func (x *DeleteRequest) GetWorkspaceId() string {
	if x != nil {
		return x.WorkspaceId
	}
	return ""
}

type DeleteResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteResponse) Reset() {
	*x = DeleteResponse{}
	mi := &file_devsy_runtime_v1_runtime_proto_msgTypes[26]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteResponse) ProtoMessage() {}

func (x *DeleteResponse) ProtoReflect() protoreflect.Message {
	mi := &file_devsy_runtime_v1_runtime_proto_msgTypes[26]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteResponse.ProtoReflect.Descriptor instead.
func (*DeleteResponse) Descriptor() ([]byte, []int) {
	return file_devsy_runtime_v1_runtime_proto_rawDescGZIP(), []int{26}
}

type ExecClientMessage struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Payload:
	//
	//	*ExecClientMessage_Start
	//	*ExecClientMessage_Stdin
	//	*ExecClientMessage_CloseStdin
	Payload       isExecClientMessage_Payload `protobuf_oneof:"payload"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExecClientMessage) Reset() {
	*x = ExecClientMessage{}
	mi := &file_devsy_runtime_v1_runtime_proto_msgTypes[27]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExecClientMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExecClientMessage) ProtoMessage() {}

func (x *ExecClientMessage) ProtoReflect() protoreflect.Message {
	mi := &file_devsy_runtime_v1_runtime_proto_msgTypes[27]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExecClientMessage.ProtoReflect.Descriptor instead.
func (*ExecClientMessage) Descriptor() ([]byte, []int) {
	return file_devsy_runtime_v1_runtime_proto_rawDescGZIP(), []int{27}
}

func (x *ExecClientMessage) GetPayload() isExecClientMessage_Payload {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *ExecClientMessage) GetStart() *ExecStart {
	if x != nil {
		if x, ok := x.Payload.(*ExecClientMessage_Start); ok {
			return x.Start
		}
	}
	return nil
}

func (x *ExecClientMessage) GetStdin() []byte {
	if x != nil {
		if x, ok := x.Payload.(*ExecClientMessage_Stdin); ok {
			return x.Stdin
		}
	}
	return nil
}

func (x *ExecClientMessage) GetCloseStdin() *CloseStdin {
	if x != nil {
		if x, ok := x.Payload.(*ExecClientMessage_CloseStdin); ok {
			return x.CloseStdin
		}
	}
	return nil
}

type isExecClientMessage_Payload interface {
	isExecClientMessage_Payload()
}

type ExecClientMessage_Start struct {
	Start *ExecStart `protobuf:"bytes,1,opt,name=start,proto3,oneof"`
}

type ExecClientMessage_Stdin struct {
	Stdin []byte `protobuf:"bytes,2,opt,name=stdin,proto3,oneof"`
}

type ExecClientMessage_CloseStdin struct {
	CloseStdin *CloseStdin `protobuf:"bytes,3,opt,name=close_stdin,json=closeStdin,proto3,oneof"`
}

func (*ExecClientMessage_Start) isExecClientMessage_Payload() {}

func (*ExecClientMessage_Stdin) isExecClientMessage_Payload() {}

func (*ExecClientMessage_CloseStdin) isExecClientMessage_Payload() {}

type ExecStart struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	WorkspaceId   string                 `protobuf:"bytes,1,opt,name=workspace_id,json=workspaceId,proto3" json:"workspace_id,omitempty"`
	Argv          []string               `protobuf:"bytes,2,rep,name=argv,proto3" json:"argv,omitempty"`
	User          string                 `protobuf:"bytes,3,opt,name=user,proto3" json:"user,omitempty"`
	Workdir       string                 `protobuf:"bytes,4,opt,name=workdir,proto3" json:"workdir,omitempty"`
	Environment   map[string]string      `protobuf:"bytes,5,rep,name=environment,proto3" json:"environment,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	Tty           bool                   `protobuf:"varint,6,opt,name=tty,proto3" json:"tty,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExecStart) Reset() {
	*x = ExecStart{}
	mi := &file_devsy_runtime_v1_runtime_proto_msgTypes[28]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExecStart) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExecStart) ProtoMessage() {}

func (x *ExecStart) ProtoReflect() protoreflect.Message {
	mi := &file_devsy_runtime_v1_runtime_proto_msgTypes[28]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExecStart.ProtoReflect.Descriptor instead.
func (*ExecStart) Descriptor() ([]byte, []int) {
	return file_devsy_runtime_v1_runtime_proto_rawDescGZIP(), []int{28}
}

func (x *ExecStart) GetWorkspaceId() string {
	if x != nil {
		return x.WorkspaceId
	}
	return ""
}

func (x *ExecStart) GetArgv() []string {
	if x != nil {
		return x.Argv
	}
	return nil
}

func (x *ExecStart) GetUser() string {
	if x != nil {
		return x.User
	}
	return ""
}

func (x *ExecStart) GetWorkdir() string {
	if x != nil {
		return x.Workdir
	}
	return ""
}

func (x *ExecStart) GetEnvironment() map[string]string {
	if x != nil {
		return x.Environment
	}
	return nil
}

func (x *ExecStart) GetTty() bool {
	if x != nil {
		return x.Tty
	}
	return false
}

type CloseStdin struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CloseStdin) Reset() {
	*x = CloseStdin{}
	mi := &file_devsy_runtime_v1_runtime_proto_msgTypes[29]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CloseStdin) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CloseStdin) ProtoMessage() {}

func (x *CloseStdin) ProtoReflect() protoreflect.Message {
	mi := &file_devsy_runtime_v1_runtime_proto_msgTypes[29]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CloseStdin.ProtoReflect.Descriptor instead.
func (*CloseStdin) Descriptor() ([]byte, []int) {
	return file_devsy_runtime_v1_runtime_proto_rawDescGZIP(), []int{29}
}

type ExecServerMessage struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Payload:
	//
	//	*ExecServerMessage_Stdout
	//	*ExecServerMessage_Stderr
	//	*ExecServerMessage_Exit
	Payload       isExecServerMessage_Payload `protobuf_oneof:"payload"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExecServerMessage) Reset() {
	*x = ExecServerMessage{}
	mi := &file_devsy_runtime_v1_runtime_proto_msgTypes[30]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExecServerMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExecServerMessage) ProtoMessage() {}

func (x *ExecServerMessage) ProtoReflect() protoreflect.Message {
	mi := &file_devsy_runtime_v1_runtime_proto_msgTypes[30]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExecServerMessage.ProtoReflect.Descriptor instead.
func (*ExecServerMessage) Descriptor() ([]byte, []int) {
	return file_devsy_runtime_v1_runtime_proto_rawDescGZIP(), []int{30}
}

func (x *ExecServerMessage) GetPayload() isExecServerMessage_Payload {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *ExecServerMessage) GetStdout() *OutputChunk {
	if x != nil {
		if x, ok := x.Payload.(*ExecServerMessage_Stdout); ok {
			return x.Stdout
		}
	}
	return nil
}

func (x *ExecServerMessage) GetStderr() *OutputChunk {
	if x != nil {
		if x, ok := x.Payload.(*ExecServerMessage_Stderr); ok {
			return x.Stderr
		}
	}
	return nil
}

func (x *ExecServerMessage) GetExit() *ExecExit {
	if x != nil {
		if x, ok := x.Payload.(*ExecServerMessage_Exit); ok {
			return x.Exit
		}
	}
	return nil
}

type isExecServerMessage_Payload interface {
	isExecServerMessage_Payload()
}

type ExecServerMessage_Stdout struct {
	Stdout *OutputChunk `protobuf:"bytes,1,opt,name=stdout,proto3,oneof"`
}

type ExecServerMessage_Stderr struct {
	Stderr *OutputChunk `protobuf:"bytes,2,opt,name=stderr,proto3,oneof"`
}

type ExecServerMessage_Exit struct {
	Exit *ExecExit `protobuf:"bytes,3,opt,name=exit,proto3,oneof"`
}

func (*ExecServerMessage_Stdout) isExecServerMessage_Payload() {}

func (*ExecServerMessage_Stderr) isExecServerMessage_Payload() {}

func (*ExecServerMessage_Exit) isExecServerMessage_Payload() {}

type OutputChunk struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Data          []byte                 `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OutputChunk) Reset() {
	*x = OutputChunk{}
	mi := &file_devsy_runtime_v1_runtime_proto_msgTypes[31]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OutputChunk) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OutputChunk) ProtoMessage() {}

func (x *OutputChunk) ProtoReflect() protoreflect.Message {
	mi := &file_devsy_runtime_v1_runtime_proto_msgTypes[31]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OutputChunk.ProtoReflect.Descriptor instead.
func (*OutputChunk) Descriptor() ([]byte, []int) {
	return file_devsy_runtime_v1_runtime_proto_rawDescGZIP(), []int{31}
}

func (x *OutputChunk) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

type ExecExit struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Command success requires exit_code == 0 AND an empty signal.
	ExitCode int32 `protobuf:"varint,1,opt,name=exit_code,json=exitCode,proto3" json:"exit_code,omitempty"`
	// A nonempty signal means failure regardless of exit_code, whose default is 0.
	Signal        string `protobuf:"bytes,2,opt,name=signal,proto3" json:"signal,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExecExit) Reset() {
	*x = ExecExit{}
	mi := &file_devsy_runtime_v1_runtime_proto_msgTypes[32]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExecExit) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExecExit) ProtoMessage() {}

func (x *ExecExit) ProtoReflect() protoreflect.Message {
	mi := &file_devsy_runtime_v1_runtime_proto_msgTypes[32]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExecExit.ProtoReflect.Descriptor instead.
func (*ExecExit) Descriptor() ([]byte, []int) {
	return file_devsy_runtime_v1_runtime_proto_rawDescGZIP(), []int{32}
}

func (x *ExecExit) GetExitCode() int32 {
	if x != nil {
		return x.ExitCode
	}
	return 0
}

func (x *ExecExit) GetSignal() string {
	if x != nil {
		return x.Signal
	}
	return ""
}

type LogsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	WorkspaceId   string                 `protobuf:"bytes,1,opt,name=workspace_id,json=workspaceId,proto3" json:"workspace_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LogsRequest) Reset() {
	*x = LogsRequest{}
	mi := &file_devsy_runtime_v1_runtime_proto_msgTypes[33]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LogsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LogsRequest) ProtoMessage() {}

func (x *LogsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_devsy_runtime_v1_runtime_proto_msgTypes[33]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LogsRequest.ProtoReflect.Descriptor instead.
func (*LogsRequest) Descriptor() ([]byte, []int) {
	return file_devsy_runtime_v1_runtime_proto_rawDescGZIP(), []int{33}
}

func (x *LogsRequest) GetWorkspaceId() string {
	if x != nil {
		return x.WorkspaceId
	}
	return ""
}

type RuntimeError struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Code           RuntimeErrorCode       `protobuf:"varint,1,opt,name=code,proto3,enum=devsy.runtime.v1.RuntimeErrorCode" json:"code,omitempty"`
	Message        string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	RuntimeMessage string                 `protobuf:"bytes,3,opt,name=runtime_message,json=runtimeMessage,proto3" json:"runtime_message,omitempty"`
	Retryable      bool                   `protobuf:"varint,4,opt,name=retryable,proto3" json:"retryable,omitempty"`
	Details        map[string]string      `protobuf:"bytes,5,rep,name=details,proto3" json:"details,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *RuntimeError) Reset() {
	*x = RuntimeError{}
	mi := &file_devsy_runtime_v1_runtime_proto_msgTypes[34]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RuntimeError) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RuntimeError) ProtoMessage() {}

func (x *RuntimeError) ProtoReflect() protoreflect.Message {
	mi := &file_devsy_runtime_v1_runtime_proto_msgTypes[34]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RuntimeError.ProtoReflect.Descriptor instead.
func (*RuntimeError) Descriptor() ([]byte, []int) {
	return file_devsy_runtime_v1_runtime_proto_rawDescGZIP(), []int{34}
}

func (x *RuntimeError) GetCode() RuntimeErrorCode {
	if x != nil {
		return x.Code
	}
	return RuntimeErrorCode_RUNTIME_ERROR_CODE_UNKNOWN
}

func (x *RuntimeError) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *RuntimeError) GetRuntimeMessage() string {
	if x != nil {
		return x.RuntimeMessage
	}
	return ""
}

func (x *RuntimeError) GetRetryable() bool {
	if x != nil {
		return x.Retryable
	}
	return false
}

func (x *RuntimeError) GetDetails() map[string]string {
	if x != nil {
		return x.Details
	}
	return nil
}

type RunImageResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RunImageResponse) Reset() {
	*x = RunImageResponse{}
	mi := &file_devsy_runtime_v1_runtime_proto_msgTypes[35]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RunImageResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RunImageResponse) ProtoMessage() {}

func (x *RunImageResponse) ProtoReflect() protoreflect.Message {
	mi := &file_devsy_runtime_v1_runtime_proto_msgTypes[35]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RunImageResponse.ProtoReflect.Descriptor instead.
func (*RunImageResponse) Descriptor() ([]byte, []int) {
	return file_devsy_runtime_v1_runtime_proto_rawDescGZIP(), []int{35}
}

var File_devsy_runtime_v1_runtime_proto protoreflect.FileDescriptor

const file_devsy_runtime_v1_runtime_proto_rawDesc = "" +
	"\n" +
	"\x1edevsy/runtime/v1/runtime.proto\x12\x10devsy.runtime.v1\"\r\n" +
	"\vInfoRequest\"\xa0\x02\n" +
	"\fInfoResponse\x12\x1b\n" +
	"\tapi_major\x18\x01 \x01(\rR\bapiMajor\x12\x1b\n" +
	"\tapi_minor\x18\x02 \x01(\rR\bapiMinor\x12\x1f\n" +
	"\vdriver_name\x18\x03 \x01(\tR\n" +
	"driverName\x12%\n" +
	"\x0edriver_version\x18\x04 \x01(\tR\rdriverVersion\x12!\n" +
	"\fruntime_name\x18\x05 \x01(\tR\vruntimeName\x12'\n" +
	"\x0fruntime_version\x18\x06 \x01(\tR\x0eruntimeVersion\x12B\n" +
	"\fcapabilities\x18\a \x01(\v2\x1e.devsy.runtime.v1.CapabilitiesR\fcapabilities\"\x9b\x03\n" +
	"\fCapabilities\x12<\n" +
	"\vmount_types\x18\x01 \x03(\x0e2\x1b.devsy.runtime.v1.MountTypeR\n" +
	"mountTypes\x128\n" +
	"\x18requires_mount_streaming\x18\x02 \x01(\bR\x16requiresMountStreaming\x128\n" +
	"\x18requires_workspace_chown\x18\x03 \x01(\bR\x16requiresWorkspaceChown\x12C\n" +
	"\rrecreate_mode\x18\x04 \x01(\x0e2\x1e.devsy.runtime.v1.RecreateModeR\frecreateMode\x125\n" +
	"\x16provisioning_preflight\x18\x05 \x01(\bR\x15provisioningPreflight\x12 \n" +
	"\vreprovision\x18\x06 \x01(\bR\vreprovision\x12\x12\n" +
	"\x04logs\x18\a \x01(\bR\x04logs\x12'\n" +
	"\x0freuse_preflight\x18\b \x01(\bR\x0ereusePreflight\"@\n" +
	"\x10PreflightRequest\x12,\n" +
	"\x12disable_auto_start\x18\x01 \x01(\bR\x10disableAutoStart\"\x13\n" +
	"\x11PreflightResponse\"\x1e\n" +
	"\x1cProvisioningPreflightRequest\"\x1f\n" +
	"\x1dProvisioningPreflightResponse\"[\n" +
	"\x15ReusePreflightRequest\x12!\n" +
	"\fworkspace_id\x18\x01 \x01(\tR\vworkspaceId\x12\x1f\n" +
	"\vremote_user\x18\x02 \x01(\tR\n" +
	"remoteUser\"\x18\n" +
	"\x16ReusePreflightResponse\"0\n" +
	"\vFindRequest\x12!\n" +
	"\fworkspace_id\x18\x01 \x01(\tR\vworkspaceId\"f\n" +
	"\fFindResponse\x12\x14\n" +
	"\x05found\x18\x01 \x01(\bR\x05found\x12@\n" +
	"\tcontainer\x18\x02 \x01(\v2\".devsy.runtime.v1.ContainerDetailsR\tcontainer\"\xee\x01\n" +
	"\x10ContainerDetails\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1d\n" +
	"\n" +
	"created_at\x18\x02 \x01(\tR\tcreatedAt\x126\n" +
	"\x05state\x18\x03 \x01(\v2 .devsy.runtime.v1.ContainerStateR\x05state\x129\n" +
	"\x06config\x18\x04 \x01(\v2!.devsy.runtime.v1.ContainerConfigR\x06config\x128\n" +
	"\x06mounts\x18\x05 \x03(\v2 .devsy.runtime.v1.ContainerMountR\x06mounts\"z\n" +
	"\x0eContainerState\x12\x16\n" +
	"\x06status\x18\x01 \x01(\tR\x06status\x12\x1d\n" +
	"\n" +
	"started_at\x18\x02 \x01(\tR\tstartedAt\x12\x1b\n" +
	"\texit_code\x18\x03 \x01(\x05R\bexitCode\x12\x14\n" +
	"\x05error\x18\x04 \x01(\tR\x05error\"\xc8\x01\n" +
	"\x0fContainerConfig\x12E\n" +
	"\x06labels\x18\x01 \x03(\v2-.devsy.runtime.v1.ContainerConfig.LabelsEntryR\x06labels\x12\x1f\n" +
	"\vworking_dir\x18\x02 \x01(\tR\n" +
	"workingDir\x12\x12\n" +
	"\x04user\x18\x03 \x01(\tR\x04user\x1a9\n" +
	"\vLabelsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"^\n" +
	"\x0eContainerMount\x12\x12\n" +
	"\x04type\x18\x01 \x01(\tR\x04type\x12\x16\n" +
	"\x06source\x18\x02 \x01(\tR\x06source\x12 \n" +
	"\vdestination\x18\x03 \x01(\tR\vdestination\">\n" +
	"\x19TargetArchitectureRequest\x12!\n" +
	"\fworkspace_id\x18\x01 \x01(\tR\vworkspaceId\"@\n" +
	"\x1aTargetArchitectureResponse\x12\"\n" +
	"\farchitecture\x18\x01 \x01(\tR\farchitecture\"\xed\x06\n" +
	"\x0fRunImageRequest\x12!\n" +
	"\fworkspace_id\x18\x01 \x01(\tR\vworkspaceId\x12\x14\n" +
	"\x05image\x18\x02 \x01(\tR\x05image\x12.\n" +
	"\x13image_built_locally\x18\x03 \x01(\bR\x11imageBuiltLocally\x12\x12\n" +
	"\x04user\x18\x04 \x01(\tR\x04user\x12\x1e\n" +
	"\n" +
	"entrypoint\x18\x05 \x01(\tR\n" +
	"entrypoint\x12\x12\n" +
	"\x04args\x18\x06 \x03(\tR\x04args\x12T\n" +
	"\venvironment\x18\a \x03(\v22.devsy.runtime.v1.RunImageRequest.EnvironmentEntryR\venvironment\x12\x16\n" +
	"\x06labels\x18\b \x03(\tR\x06labels\x12\x17\n" +
	"\acap_add\x18\t \x03(\tR\x06capAdd\x12!\n" +
	"\fsecurity_opt\x18\n" +
	" \x03(\tR\vsecurityOpt\x12#\n" +
	"\n" +
	"privileged\x18\v \x01(\bH\x00R\n" +
	"privileged\x88\x01\x01\x12\x17\n" +
	"\x04init\x18\f \x01(\bH\x01R\x04init\x88\x01\x01\x12@\n" +
	"\x0fworkspace_mount\x18\r \x01(\v2\x17.devsy.runtime.v1.MountR\x0eworkspaceMount\x12/\n" +
	"\x06mounts\x18\x0e \x03(\v2\x17.devsy.runtime.v1.MountR\x06mounts\x12\x16\n" +
	"\x06userns\x18\x0f \x01(\tR\x06userns\x12\x17\n" +
	"\auid_map\x18\x10 \x03(\tR\x06uidMap\x12\x17\n" +
	"\agid_map\x18\x11 \x03(\tR\x06gidMap\x12\x1a\n" +
	"\bplatform\x18\x12 \x01(\tR\bplatform\x12O\n" +
	"\x11host_requirements\x18\x13 \x01(\v2\".devsy.runtime.v1.HostRequirementsR\x10hostRequirements\x12\x1f\n" +
	"\vremote_user\x18\x14 \x01(\tR\n" +
	"remoteUser\x12\x1e\n" +
	"\n" +
	"dockerless\x18\x15 \x01(\bR\n" +
	"dockerless\x1a>\n" +
	"\x10EnvironmentEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01B\r\n" +
	"\v_privilegedB\a\n" +
	"\x05_init\"\x9f\x01\n" +
	"\x05Mount\x12/\n" +
	"\x04type\x18\x01 \x01(\x0e2\x1b.devsy.runtime.v1.MountTypeR\x04type\x12\x16\n" +
	"\x06source\x18\x02 \x01(\tR\x06source\x12\x16\n" +
	"\x06target\x18\x03 \x01(\tR\x06target\x12\x1b\n" +
	"\tread_only\x18\x04 \x01(\bR\breadOnly\x12\x18\n" +
	"\aoptions\x18\x05 \x03(\tR\aoptions\"\xa2\x01\n" +
	"\x10HostRequirements\x12\x12\n" +
	"\x04cpus\x18\x01 \x01(\x05R\x04cpus\x12!\n" +
	"\fmemory_bytes\x18\x02 \x01(\x04R\vmemoryBytes\x12#\n" +
	"\rstorage_bytes\x18\x03 \x01(\x04R\fstorageBytes\x122\n" +
	"\x03gpu\x18\x04 \x01(\v2 .devsy.runtime.v1.GpuRequirementR\x03gpu\"M\n" +
	"\x0eGpuRequirement\x12;\n" +
	"\x05value\x18\x01 \x01(\x0e2%.devsy.runtime.v1.GpuRequirementValueR\x05value\"1\n" +
	"\fStartRequest\x12!\n" +
	"\fworkspace_id\x18\x01 \x01(\tR\vworkspaceId\"\x0f\n" +
	"\rStartResponse\"0\n" +
	"\vStopRequest\x12!\n" +
	"\fworkspace_id\x18\x01 \x01(\tR\vworkspaceId\"\x0e\n" +
	"\fStopResponse\"2\n" +
	"\rDeleteRequest\x12!\n" +
	"\fworkspace_id\x18\x01 \x01(\tR\vworkspaceId\"\x10\n" +
	"\x0eDeleteResponse\"\xac\x01\n" +
	"\x11ExecClientMessage\x123\n" +
	"\x05start\x18\x01 \x01(\v2\x1b.devsy.runtime.v1.ExecStartH\x00R\x05start\x12\x16\n" +
	"\x05stdin\x18\x02 \x01(\fH\x00R\x05stdin\x12?\n" +
	"\vclose_stdin\x18\x03 \x01(\v2\x1c.devsy.runtime.v1.CloseStdinH\x00R\n" +
	"closeStdinB\t\n" +
	"\apayload\"\x92\x02\n" +
	"\tExecStart\x12!\n" +
	"\fworkspace_id\x18\x01 \x01(\tR\vworkspaceId\x12\x12\n" +
	"\x04argv\x18\x02 \x03(\tR\x04argv\x12\x12\n" +
	"\x04user\x18\x03 \x01(\tR\x04user\x12\x18\n" +
	"\aworkdir\x18\x04 \x01(\tR\aworkdir\x12N\n" +
	"\venvironment\x18\x05 \x03(\v2,.devsy.runtime.v1.ExecStart.EnvironmentEntryR\venvironment\x12\x10\n" +
	"\x03tty\x18\x06 \x01(\bR\x03tty\x1a>\n" +
	"\x10EnvironmentEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\f\n" +
	"\n" +
	"CloseStdin\"\xc2\x01\n" +
	"\x11ExecServerMessage\x127\n" +
	"\x06stdout\x18\x01 \x01(\v2\x1d.devsy.runtime.v1.OutputChunkH\x00R\x06stdout\x127\n" +
	"\x06stderr\x18\x02 \x01(\v2\x1d.devsy.runtime.v1.OutputChunkH\x00R\x06stderr\x120\n" +
	"\x04exit\x18\x03 \x01(\v2\x1a.devsy.runtime.v1.ExecExitH\x00R\x04exitB\t\n" +
	"\apayload\"!\n" +
	"\vOutputChunk\x12\x12\n" +
	"\x04data\x18\x01 \x01(\fR\x04data\"?\n" +
	"\bExecExit\x12\x1b\n" +
	"\texit_code\x18\x01 \x01(\x05R\bexitCode\x12\x16\n" +
	"\x06signal\x18\x02 \x01(\tR\x06signal\"0\n" +
	"\vLogsRequest\x12!\n" +
	"\fworkspace_id\x18\x01 \x01(\tR\vworkspaceId\"\xaa\x02\n" +
	"\fRuntimeError\x126\n" +
	"\x04code\x18\x01 \x01(\x0e2\".devsy.runtime.v1.RuntimeErrorCodeR\x04code\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12'\n" +
	"\x0fruntime_message\x18\x03 \x01(\tR\x0eruntimeMessage\x12\x1c\n" +
	"\tretryable\x18\x04 \x01(\bR\tretryable\x12E\n" +
	"\adetails\x18\x05 \x03(\v2+.devsy.runtime.v1.RuntimeError.DetailsEntryR\adetails\x1a:\n" +
	"\fDetailsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\x12\n" +
	"\x10RunImageResponse*i\n" +
	"\tMountType\x12\x1a\n" +
	"\x16MOUNT_TYPE_UNSPECIFIED\x10\x00\x12\x13\n" +
	"\x0fMOUNT_TYPE_BIND\x10\x01\x12\x15\n" +
	"\x11MOUNT_TYPE_VOLUME\x10\x02\x12\x14\n" +
	"\x10MOUNT_TYPE_TMPFS\x10\x03*_\n" +
	"\fRecreateMode\x12\x1d\n" +
	"\x19RECREATE_MODE_UNSPECIFIED\x10\x00\x12\x18\n" +
	"\x14RECREATE_MODE_DELETE\x10\x01\x12\x16\n" +
	"\x12RECREATE_MODE_STOP\x10\x02*]\n" +
	"\x13GpuRequirementValue\x12\x13\n" +
	"\x0fGPU_UNSPECIFIED\x10\x00\x12\r\n" +
	"\tGPU_FALSE\x10\x01\x12\x10\n" +
	"\fGPU_OPTIONAL\x10\x02\x12\x10\n" +
	"\fGPU_REQUIRED\x10\x03*\xd9\x03\n" +
	"\x10RuntimeErrorCode\x12\x1e\n" +
	"\x1aRUNTIME_ERROR_CODE_UNKNOWN\x10\x00\x12 \n" +
	"\x1cRUNTIME_ERROR_CODE_NOT_FOUND\x10\x01\x12%\n" +
	"!RUNTIME_ERROR_CODE_ALREADY_EXISTS\x10\x02\x12'\n" +
	"#RUNTIME_ERROR_CODE_INVALID_ARGUMENT\x10\x03\x12\"\n" +
	"\x1eRUNTIME_ERROR_CODE_UNSUPPORTED\x10\x04\x12\"\n" +
	"\x1eRUNTIME_ERROR_CODE_UNAVAILABLE\x10\x05\x12*\n" +
	"&RUNTIME_ERROR_CODE_FAILED_PRECONDITION\x10\x06\x12(\n" +
	"$RUNTIME_ERROR_CODE_PERMISSION_DENIED\x10\a\x12\x1e\n" +
	"\x1aRUNTIME_ERROR_CODE_TIMEOUT\x10\b\x12 \n" +
	"\x1cRUNTIME_ERROR_CODE_CANCELLED\x10\t\x12&\n" +
	"\"RUNTIME_ERROR_CODE_RUNTIME_FAILURE\x10\n" +
	"\x12+\n" +
	"'RUNTIME_ERROR_CODE_INCOMPATIBLE_VERSION\x10\v2\x92\b\n" +
	"\rRuntimeDriver\x12E\n" +
	"\x04Info\x12\x1d.devsy.runtime.v1.InfoRequest\x1a\x1e.devsy.runtime.v1.InfoResponse\x12T\n" +
	"\tPreflight\x12\".devsy.runtime.v1.PreflightRequest\x1a#.devsy.runtime.v1.PreflightResponse\x12x\n" +
	"\x15ProvisioningPreflight\x12..devsy.runtime.v1.ProvisioningPreflightRequest\x1a/.devsy.runtime.v1.ProvisioningPreflightResponse\x12c\n" +
	"\x0eReusePreflight\x12'.devsy.runtime.v1.ReusePreflightRequest\x1a(.devsy.runtime.v1.ReusePreflightResponse\x12E\n" +
	"\x04Find\x12\x1d.devsy.runtime.v1.FindRequest\x1a\x1e.devsy.runtime.v1.FindResponse\x12o\n" +
	"\x12TargetArchitecture\x12+.devsy.runtime.v1.TargetArchitectureRequest\x1a,.devsy.runtime.v1.TargetArchitectureResponse\x12Q\n" +
	"\bRunImage\x12!.devsy.runtime.v1.RunImageRequest\x1a\".devsy.runtime.v1.RunImageResponse\x12H\n" +
	"\x05Start\x12\x1e.devsy.runtime.v1.StartRequest\x1a\x1f.devsy.runtime.v1.StartResponse\x12E\n" +
	"\x04Stop\x12\x1d.devsy.runtime.v1.StopRequest\x1a\x1e.devsy.runtime.v1.StopResponse\x12K\n" +
	"\x06Delete\x12\x1f.devsy.runtime.v1.DeleteRequest\x1a .devsy.runtime.v1.DeleteResponse\x12T\n" +
	"\x04Exec\x12#.devsy.runtime.v1.ExecClientMessage\x1a#.devsy.runtime.v1.ExecServerMessage(\x010\x01\x12F\n" +
	"\x04Logs\x12\x1d.devsy.runtime.v1.LogsRequest\x1a\x1d.devsy.runtime.v1.OutputChunk0\x01B<Z:github.com/devsy-org/devsy-runtime-sdk/runtimev1;runtimev1b\x06proto3"

var (
	file_devsy_runtime_v1_runtime_proto_rawDescOnce sync.Once
	file_devsy_runtime_v1_runtime_proto_rawDescData []byte
)

func file_devsy_runtime_v1_runtime_proto_rawDescGZIP() []byte {
	file_devsy_runtime_v1_runtime_proto_rawDescOnce.Do(func() {
		file_devsy_runtime_v1_runtime_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_devsy_runtime_v1_runtime_proto_rawDesc), len(file_devsy_runtime_v1_runtime_proto_rawDesc)))
	})
	return file_devsy_runtime_v1_runtime_proto_rawDescData
}

var file_devsy_runtime_v1_runtime_proto_enumTypes = make([]protoimpl.EnumInfo, 4)
var file_devsy_runtime_v1_runtime_proto_msgTypes = make([]protoimpl.MessageInfo, 40)
var file_devsy_runtime_v1_runtime_proto_goTypes = []any{
	(MountType)(0),                        // 0: devsy.runtime.v1.MountType
	(RecreateMode)(0),                     // 1: devsy.runtime.v1.RecreateMode
	(GpuRequirementValue)(0),              // 2: devsy.runtime.v1.GpuRequirementValue
	(RuntimeErrorCode)(0),                 // 3: devsy.runtime.v1.RuntimeErrorCode
	(*InfoRequest)(nil),                   // 4: devsy.runtime.v1.InfoRequest
	(*InfoResponse)(nil),                  // 5: devsy.runtime.v1.InfoResponse
	(*Capabilities)(nil),                  // 6: devsy.runtime.v1.Capabilities
	(*PreflightRequest)(nil),              // 7: devsy.runtime.v1.PreflightRequest
	(*PreflightResponse)(nil),             // 8: devsy.runtime.v1.PreflightResponse
	(*ProvisioningPreflightRequest)(nil),  // 9: devsy.runtime.v1.ProvisioningPreflightRequest
	(*ProvisioningPreflightResponse)(nil), // 10: devsy.runtime.v1.ProvisioningPreflightResponse
	(*ReusePreflightRequest)(nil),         // 11: devsy.runtime.v1.ReusePreflightRequest
	(*ReusePreflightResponse)(nil),        // 12: devsy.runtime.v1.ReusePreflightResponse
	(*FindRequest)(nil),                   // 13: devsy.runtime.v1.FindRequest
	(*FindResponse)(nil),                  // 14: devsy.runtime.v1.FindResponse
	(*ContainerDetails)(nil),              // 15: devsy.runtime.v1.ContainerDetails
	(*ContainerState)(nil),                // 16: devsy.runtime.v1.ContainerState
	(*ContainerConfig)(nil),               // 17: devsy.runtime.v1.ContainerConfig
	(*ContainerMount)(nil),                // 18: devsy.runtime.v1.ContainerMount
	(*TargetArchitectureRequest)(nil),     // 19: devsy.runtime.v1.TargetArchitectureRequest
	(*TargetArchitectureResponse)(nil),    // 20: devsy.runtime.v1.TargetArchitectureResponse
	(*RunImageRequest)(nil),               // 21: devsy.runtime.v1.RunImageRequest
	(*Mount)(nil),                         // 22: devsy.runtime.v1.Mount
	(*HostRequirements)(nil),              // 23: devsy.runtime.v1.HostRequirements
	(*GpuRequirement)(nil),                // 24: devsy.runtime.v1.GpuRequirement
	(*StartRequest)(nil),                  // 25: devsy.runtime.v1.StartRequest
	(*StartResponse)(nil),                 // 26: devsy.runtime.v1.StartResponse
	(*StopRequest)(nil),                   // 27: devsy.runtime.v1.StopRequest
	(*StopResponse)(nil),                  // 28: devsy.runtime.v1.StopResponse
	(*DeleteRequest)(nil),                 // 29: devsy.runtime.v1.DeleteRequest
	(*DeleteResponse)(nil),                // 30: devsy.runtime.v1.DeleteResponse
	(*ExecClientMessage)(nil),             // 31: devsy.runtime.v1.ExecClientMessage
	(*ExecStart)(nil),                     // 32: devsy.runtime.v1.ExecStart
	(*CloseStdin)(nil),                    // 33: devsy.runtime.v1.CloseStdin
	(*ExecServerMessage)(nil),             // 34: devsy.runtime.v1.ExecServerMessage
	(*OutputChunk)(nil),                   // 35: devsy.runtime.v1.OutputChunk
	(*ExecExit)(nil),                      // 36: devsy.runtime.v1.ExecExit
	(*LogsRequest)(nil),                   // 37: devsy.runtime.v1.LogsRequest
	(*RuntimeError)(nil),                  // 38: devsy.runtime.v1.RuntimeError
	(*RunImageResponse)(nil),              // 39: devsy.runtime.v1.RunImageResponse
	nil,                                   // 40: devsy.runtime.v1.ContainerConfig.LabelsEntry
	nil,                                   // 41: devsy.runtime.v1.RunImageRequest.EnvironmentEntry
	nil,                                   // 42: devsy.runtime.v1.ExecStart.EnvironmentEntry
	nil,                                   // 43: devsy.runtime.v1.RuntimeError.DetailsEntry
}
var file_devsy_runtime_v1_runtime_proto_depIdxs = []int32{
	6,  // 0: devsy.runtime.v1.InfoResponse.capabilities:type_name -> devsy.runtime.v1.Capabilities
	0,  // 1: devsy.runtime.v1.Capabilities.mount_types:type_name -> devsy.runtime.v1.MountType
	1,  // 2: devsy.runtime.v1.Capabilities.recreate_mode:type_name -> devsy.runtime.v1.RecreateMode
	15, // 3: devsy.runtime.v1.FindResponse.container:type_name -> devsy.runtime.v1.ContainerDetails
	16, // 4: devsy.runtime.v1.ContainerDetails.state:type_name -> devsy.runtime.v1.ContainerState
	17, // 5: devsy.runtime.v1.ContainerDetails.config:type_name -> devsy.runtime.v1.ContainerConfig
	18, // 6: devsy.runtime.v1.ContainerDetails.mounts:type_name -> devsy.runtime.v1.ContainerMount
	40, // 7: devsy.runtime.v1.ContainerConfig.labels:type_name -> devsy.runtime.v1.ContainerConfig.LabelsEntry
	41, // 8: devsy.runtime.v1.RunImageRequest.environment:type_name -> devsy.runtime.v1.RunImageRequest.EnvironmentEntry
	22, // 9: devsy.runtime.v1.RunImageRequest.workspace_mount:type_name -> devsy.runtime.v1.Mount
	22, // 10: devsy.runtime.v1.RunImageRequest.mounts:type_name -> devsy.runtime.v1.Mount
	23, // 11: devsy.runtime.v1.RunImageRequest.host_requirements:type_name -> devsy.runtime.v1.HostRequirements
	0,  // 12: devsy.runtime.v1.Mount.type:type_name -> devsy.runtime.v1.MountType
	24, // 13: devsy.runtime.v1.HostRequirements.gpu:type_name -> devsy.runtime.v1.GpuRequirement
	2,  // 14: devsy.runtime.v1.GpuRequirement.value:type_name -> devsy.runtime.v1.GpuRequirementValue
	32, // 15: devsy.runtime.v1.ExecClientMessage.start:type_name -> devsy.runtime.v1.ExecStart
	33, // 16: devsy.runtime.v1.ExecClientMessage.close_stdin:type_name -> devsy.runtime.v1.CloseStdin
	42, // 17: devsy.runtime.v1.ExecStart.environment:type_name -> devsy.runtime.v1.ExecStart.EnvironmentEntry
	35, // 18: devsy.runtime.v1.ExecServerMessage.stdout:type_name -> devsy.runtime.v1.OutputChunk
	35, // 19: devsy.runtime.v1.ExecServerMessage.stderr:type_name -> devsy.runtime.v1.OutputChunk
	36, // 20: devsy.runtime.v1.ExecServerMessage.exit:type_name -> devsy.runtime.v1.ExecExit
	3,  // 21: devsy.runtime.v1.RuntimeError.code:type_name -> devsy.runtime.v1.RuntimeErrorCode
	43, // 22: devsy.runtime.v1.RuntimeError.details:type_name -> devsy.runtime.v1.RuntimeError.DetailsEntry
	4,  // 23: devsy.runtime.v1.RuntimeDriver.Info:input_type -> devsy.runtime.v1.InfoRequest
	7,  // 24: devsy.runtime.v1.RuntimeDriver.Preflight:input_type -> devsy.runtime.v1.PreflightRequest
	9,  // 25: devsy.runtime.v1.RuntimeDriver.ProvisioningPreflight:input_type -> devsy.runtime.v1.ProvisioningPreflightRequest
	11, // 26: devsy.runtime.v1.RuntimeDriver.ReusePreflight:input_type -> devsy.runtime.v1.ReusePreflightRequest
	13, // 27: devsy.runtime.v1.RuntimeDriver.Find:input_type -> devsy.runtime.v1.FindRequest
	19, // 28: devsy.runtime.v1.RuntimeDriver.TargetArchitecture:input_type -> devsy.runtime.v1.TargetArchitectureRequest
	21, // 29: devsy.runtime.v1.RuntimeDriver.RunImage:input_type -> devsy.runtime.v1.RunImageRequest
	25, // 30: devsy.runtime.v1.RuntimeDriver.Start:input_type -> devsy.runtime.v1.StartRequest
	27, // 31: devsy.runtime.v1.RuntimeDriver.Stop:input_type -> devsy.runtime.v1.StopRequest
	29, // 32: devsy.runtime.v1.RuntimeDriver.Delete:input_type -> devsy.runtime.v1.DeleteRequest
	31, // 33: devsy.runtime.v1.RuntimeDriver.Exec:input_type -> devsy.runtime.v1.ExecClientMessage
	37, // 34: devsy.runtime.v1.RuntimeDriver.Logs:input_type -> devsy.runtime.v1.LogsRequest
	5,  // 35: devsy.runtime.v1.RuntimeDriver.Info:output_type -> devsy.runtime.v1.InfoResponse
	8,  // 36: devsy.runtime.v1.RuntimeDriver.Preflight:output_type -> devsy.runtime.v1.PreflightResponse
	10, // 37: devsy.runtime.v1.RuntimeDriver.ProvisioningPreflight:output_type -> devsy.runtime.v1.ProvisioningPreflightResponse
	12, // 38: devsy.runtime.v1.RuntimeDriver.ReusePreflight:output_type -> devsy.runtime.v1.ReusePreflightResponse
	14, // 39: devsy.runtime.v1.RuntimeDriver.Find:output_type -> devsy.runtime.v1.FindResponse
	20, // 40: devsy.runtime.v1.RuntimeDriver.TargetArchitecture:output_type -> devsy.runtime.v1.TargetArchitectureResponse
	39, // 41: devsy.runtime.v1.RuntimeDriver.RunImage:output_type -> devsy.runtime.v1.RunImageResponse
	26, // 42: devsy.runtime.v1.RuntimeDriver.Start:output_type -> devsy.runtime.v1.StartResponse
	28, // 43: devsy.runtime.v1.RuntimeDriver.Stop:output_type -> devsy.runtime.v1.StopResponse
	30, // 44: devsy.runtime.v1.RuntimeDriver.Delete:output_type -> devsy.runtime.v1.DeleteResponse
	34, // 45: devsy.runtime.v1.RuntimeDriver.Exec:output_type -> devsy.runtime.v1.ExecServerMessage
	35, // 46: devsy.runtime.v1.RuntimeDriver.Logs:output_type -> devsy.runtime.v1.OutputChunk
	35, // [35:47] is the sub-list for method output_type
	23, // [23:35] is the sub-list for method input_type
	23, // [23:23] is the sub-list for extension type_name
	23, // [23:23] is the sub-list for extension extendee
	0,  // [0:23] is the sub-list for field type_name
}

func init() { file_devsy_runtime_v1_runtime_proto_init() }
func file_devsy_runtime_v1_runtime_proto_init() {
	if File_devsy_runtime_v1_runtime_proto != nil {
		return
	}
	file_devsy_runtime_v1_runtime_proto_msgTypes[17].OneofWrappers = []any{}
	file_devsy_runtime_v1_runtime_proto_msgTypes[27].OneofWrappers = []any{
		(*ExecClientMessage_Start)(nil),
		(*ExecClientMessage_Stdin)(nil),
		(*ExecClientMessage_CloseStdin)(nil),
	}
	file_devsy_runtime_v1_runtime_proto_msgTypes[30].OneofWrappers = []any{
		(*ExecServerMessage_Stdout)(nil),
		(*ExecServerMessage_Stderr)(nil),
		(*ExecServerMessage_Exit)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_devsy_runtime_v1_runtime_proto_rawDesc), len(file_devsy_runtime_v1_runtime_proto_rawDesc)),
			NumEnums:      4,
			NumMessages:   40,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_devsy_runtime_v1_runtime_proto_goTypes,
		DependencyIndexes: file_devsy_runtime_v1_runtime_proto_depIdxs,
		EnumInfos:         file_devsy_runtime_v1_runtime_proto_enumTypes,
		MessageInfos:      file_devsy_runtime_v1_runtime_proto_msgTypes,
	}.Build()
	File_devsy_runtime_v1_runtime_proto = out.File
	file_devsy_runtime_v1_runtime_proto_goTypes = nil
	file_devsy_runtime_v1_runtime_proto_depIdxs = nil
}
